# Generated by Django 3.1.7 on 2021-04-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название тэга')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveIntegerField(unique=True, verbose_name='Номер задания')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Количество баллов за выполненное задание')),
                ('categorys', models.ManyToManyField(to='mainapp.Category', verbose_name='Категории')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(verbose_name='Текст к заданию')),
                ('firstAsk', models.TextField(verbose_name='Первый вопрос')),
                ('secondAsk', models.TextField(blank=True, verbose_name='Второй вопрос')),
                ('thirdAsk', models.TextField(blank=True, verbose_name='Третий вопрос')),
                ('imgForAsk', models.ImageField(blank=True, null=True, upload_to='imgForAsk', verbose_name='Картинка для вопроса')),
                ('imgForAns', models.ImageField(blank=True, null=True, upload_to='imgForAns', verbose_name='Картинка для ответа')),
                ('fistInstruction', models.TextField(verbose_name='инструкция к первому вопросу')),
                ('secondInstuction', models.TextField(blank=True, verbose_name='инструкция к второму вопросу')),
                ('thirdIntroduction', models.TextField(blank=True, verbose_name='инструкция к третьему вопросу')),
                ('firstAnswer', models.CharField(max_length=100, verbose_name='Ответ на первый вопрос')),
                ('secondAnwer', models.CharField(blank=True, max_length=100, verbose_name='Ответ на второй вопрос')),
                ('thirdAnswer', models.CharField(blank=True, max_length=100, verbose_name='Ответ на третий вопрос')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категории')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.number', verbose_name='Номер задания')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variantNumber', models.PositiveIntegerField(unique=True, verbose_name='Номер варианта')),
                ('questions', models.ManyToManyField(to='mainapp.Question', verbose_name='Задания, которые будут в этом варианте')),
            ],
        ),
    ]
