# Generated by Django 3.1.7 on 2021-04-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Номер задания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='difficult',
            field=models.PositiveIntegerField(default=1, verbose_name='Сложность задания по 10-ти бальной шкале'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='number',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='categorys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
    ]
