# Generated by Django 3.1.7 on 2021-04-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210405_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='addition',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название источника'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_link',
            field=models.TextField(blank=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='question',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Текст к заданию'),
        ),
    ]
