# Generated by Django 3.1.7 on 2021-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210405_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название критерия')),
                ('points', models.PositiveIntegerField(verbose_name='Максимальное кол-во баллов')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='benchmarks',
            field=models.ManyToManyField(to='mainapp.Benchmark', verbose_name='Критерии (Только для 2-ой части!)'),
        ),
    ]
