# Generated by Django 3.1.7 on 2021-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210417_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='benchmarks',
        ),
        migrations.AddField(
            model_name='number',
            name='benchmarks',
            field=models.ManyToManyField(blank=True, to='mainapp.Benchmark', verbose_name='Критерии (Только для 2-ой части!)'),
        ),
    ]
