# Generated by Django 3.1.7 on 2021-04-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210417_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название материала')),
                ('text', models.TextField(verbose_name='Текст материала')),
                ('imgMaterial', models.ImageField(blank=True, null=True, upload_to='imgForMaterials', verbose_name='Картинка для материала')),
            ],
        ),
        migrations.AddField(
            model_name='number',
            name='materials',
            field=models.ManyToManyField(to='mainapp.Material', verbose_name='Материалы к заданию'),
        ),
    ]
